-- ==============================================
-- Setup da tabela de contatos no Supabase
-- Execute este SQL no SQL Editor do Supabase
-- ==============================================

-- Cria a tabela de contatos
CREATE TABLE IF NOT EXISTS contatos (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_contato TEXT NOT NULL,
    telefone    TEXT NOT NULL,
    ativo       BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

-- Insere contatos de exemplo para teste
INSERT INTO contatos (nome_contato, telefone, ativo)
VALUES
    ('Contato Teste 1', '5511999999999', true),
    ('Contato Teste 2', '5511988888888', true),
    ('Contato Teste 3', '5511977777777', true);

-- Verificar os registros inseridos
SELECT * FROM contatos;
